set(DEM_TOOLS_COMMON_HEADERS
	ContentForgeTool.h
	Data.h
	DataScheme.h
	HRDParser.h
	Logging.h
	MurmurHash3.h
	ParamsUtils.h
	StringID.h
	StringIDStorage.h
	Type.h
	Utils.h
	ValueTable.h
	ShaderMeta/SM30ShaderMeta.h
	ShaderMeta/USMShaderMeta.h
)

set(DEM_TOOLS_COMMON_SOURCES
	ContentForgeTool.cpp
	Data.cpp
	DataScheme.cpp
	HRDParser.cpp
	MurmurHash3.cpp
	ParamsUtils.cpp
	StringID.cpp
	StringIDStorage.cpp
	Utils.cpp
	ValueTable.cpp
	ShaderMeta/SM30ShaderMeta.cpp
	ShaderMeta/USMShaderMeta.cpp
)

