set(DEM_SHADER_COMPILER_HEADERS
	src/Buffer.h
	src/D3D9ShaderReflectionAPI.h
	src/Data.h
	src/DEMD3DInclude.h
	src/DEMShaderCompilerDLL.h
	src/MurmurHash3.h
	src/ShaderCompiler.h
	src/ShaderDB.h
	src/ShaderReflection.h
	src/ShaderReflectionSM30.h
	src/ShaderReflectionUSM.h
	src/StringID.h
	src/StringIDStorage.h
	src/Type.h
	src/ValueTable.h
)

set(DEM_SHADER_COMPILER_SOURCES
	src/Buffer.cpp
	src/D3D9ShaderReflectionAPI.cpp
	src/Data.cpp
	src/DEMD3DInclude.cpp
	src/DEMShaderCompilerDLL.cpp
	src/Main.cpp
	src/MurmurHash3.cpp
	src/ShaderCompiler.cpp
	src/ShaderDB.cpp
	src/ShaderReflectionSM30.cpp
	src/ShaderReflectionUSM.cpp
	src/StringID.cpp
	src/StringIDStorage.cpp
	src/ValueTable.cpp
)

