//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorIDE.Package {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreatorIDE.Package.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project is empty..
        /// </summary>
        internal static string EmptyNodeCaption {
            get {
                return ResourceManager.GetString("EmptyNodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; not found..
        /// </summary>
        internal static string FileNotFoundFormatString {
            get {
                return ResourceManager.GetString("FileNotFoundFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Path.
        /// </summary>
        internal static string FullPathPropertyName {
            get {
                return ResourceManager.GetString("FullPathPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level database file.
        /// </summary>
        internal static string LevelDatabaseFile {
            get {
                return ResourceManager.GetString("LevelDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Browser.
        /// </summary>
        internal static string LevelObjectBrowserCaption {
            get {
                return ResourceManager.GetString("LevelObjectBrowserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string MiscCategoryName {
            get {
                return ResourceManager.GetString("MiscCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open level database file.
        /// </summary>
        internal static string OpenLevelDatabaseFile {
            get {
                return ResourceManager.GetString("OpenLevelDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Path.
        /// </summary>
        internal static string PackagePathPropertyName {
            get {
                return ResourceManager.GetString("PackagePathPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Path.
        /// </summary>
        internal static string RelativePathPropertyName {
            get {
                return ResourceManager.GetString("RelativePathPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &quot;{0}&quot; is already deaclared as the default scope for folder &quot;{1}&quot;..
        /// </summary>
        internal static string ScopeIsAlreadyDeclaredFormatString {
            get {
                return ResourceManager.GetString("ScopeIsAlreadyDeclaredFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid name for a resource scope..
        /// </summary>
        internal static string ScopeNameIsInvalidFormatString {
            get {
                return ResourceManager.GetString("ScopeNameIsInvalidFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of resource scope must contain at least two characters..
        /// </summary>
        internal static string ScopeNameIsTooShort {
            get {
                return ResourceManager.GetString("ScopeNameIsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Scope.
        /// </summary>
        internal static string ScopePropertyName {
            get {
                return ResourceManager.GetString("ScopePropertyName", resourceCulture);
            }
        }
    }
}
