set(DEM_L2_GAME_HEADERS
	DEM/Game/src/AI/AILevel.h
	DEM/Game/src/AI/AIStateComponent.h
	DEM/Game/src/AI/FormationManager.h
	DEM/Game/src/AI/MoveInteraction.h
	DEM/Game/src/AI/Behaviour/BehaviourTreeAsset.h
	DEM/Game/src/AI/Behaviour/BehaviourTreeAssetLoader.h
	DEM/Game/src/AI/Behaviour/BehaviourTreeCondition.h
	DEM/Game/src/AI/Behaviour/BehaviourTreeExecuteAbility.h
	DEM/Game/src/AI/Behaviour/BehaviourTreePlayer.h
	DEM/Game/src/AI/Behaviour/BehaviourTreeSelector.h
	DEM/Game/src/AI/Behaviour/BehaviourTreeSequence.h
	DEM/Game/src/AI/Movement/SteerAction.h
	DEM/Game/src/AI/Navigation/NavAgentComponent.h
	DEM/Game/src/AI/Navigation/NavAgentSettings.h
	DEM/Game/src/AI/Navigation/NavAgentSettingsLoaderHRD.h
	DEM/Game/src/AI/Navigation/NavControllerComponent.h
	DEM/Game/src/AI/Navigation/NavFwd.h
	DEM/Game/src/AI/Navigation/NavMap.h
	DEM/Game/src/AI/Navigation/NavMesh.h
	DEM/Game/src/AI/Navigation/NavMeshDebugDraw.h
	DEM/Game/src/AI/Navigation/NavMeshLoaderNM.h
	DEM/Game/src/AI/Navigation/PathRequestQueue.h
	DEM/Game/src/AI/Navigation/TraversalAction.h
	DEM/Game/src/AI/Perception/Perception.h
	DEM/Game/src/AI/Perception/SoundSensorComponent.h
	DEM/Game/src/AI/Perception/SoundStimulus.h
	DEM/Game/src/AI/Perception/VisibleComponent.h
	DEM/Game/src/AI/Perception/VisionSensorComponent.h
	DEM/Game/src/Animation/AnimationComponent.h
	DEM/Game/src/Animation/TimelineTask.h
	DEM/Game/src/App/AppFSM.h
	DEM/Game/src/App/AppStateVideo.h
	DEM/Game/src/App/StateHandler.h
	DEM/Game/src/Game/Entity.h
	DEM/Game/src/Game/GameLevel.h
	DEM/Game/src/Game/GameSession.h
	DEM/Game/src/Game/GameState.h
	DEM/Game/src/Game/GameStateManager.h
	DEM/Game/src/Game/Property.h
	DEM/Game/src/Game/SessionVars.h
	DEM/Game/src/Game/ECS/ComponentObserver.h
	DEM/Game/src/Game/ECS/ComponentStorage.h
	DEM/Game/src/Game/ECS/Entity.h
	DEM/Game/src/Game/ECS/EntityMap.h
	DEM/Game/src/Game/ECS/EntityTemplate.h
	DEM/Game/src/Game/ECS/EntityTemplateLoader.h
	DEM/Game/src/Game/ECS/GameWorld.h
	DEM/Game/src/Game/ECS/Components/ActionQueueComponent.h
	DEM/Game/src/Game/ECS/Components/EventsComponent.h
	DEM/Game/src/Game/Interaction/Ability.h
	DEM/Game/src/Game/Interaction/AbilityInstance.h
	DEM/Game/src/Game/Interaction/Interaction.h
	DEM/Game/src/Game/Interaction/InteractionContext.h
	DEM/Game/src/Game/Interaction/InteractionManager.h
	DEM/Game/src/Game/Interaction/InteractionTool.h
	DEM/Game/src/Game/Interaction/ScriptedAbility.h
	DEM/Game/src/Game/Interaction/ScriptedInteraction.h
	DEM/Game/src/Game/Interaction/SelectableComponent.h
	DEM/Game/src/Game/Interaction/SelectInteraction.h
	DEM/Game/src/Game/Interaction/Zone.h
	DEM/Game/src/Game/Objects/SmartObject.h
	DEM/Game/src/Game/Objects/SmartObjectComponent.h
	DEM/Game/src/Game/Objects/SmartObjectLoader.h
	DEM/Game/src/Physics/CharacterControllerComponent.h
	DEM/Game/src/Physics/PropTrigger.h
	DEM/Game/src/Physics/RigidBodyComponent.h
	DEM/Game/src/Scene/SceneComponent.h
	DEM/Game/src/Scripting/EntityScriptObject.h
	DEM/Game/src/Scripting/PropScriptable.h
	DEM/Game/src/Scripting/SolGame.h
	DEM/Game/src/Scripting/Flow/Condition.h
	DEM/Game/src/Scripting/Flow/ConditionRegistry.h
	DEM/Game/src/Scripting/Flow/FlowAsset.h
	DEM/Game/src/Scripting/Flow/FlowAssetLoader.h
	DEM/Game/src/Scripting/Flow/FlowCommon.h
	DEM/Game/src/Scripting/Flow/FlowPlayer.h
	DEM/Game/src/Scripting/Flow/HubAction.h
	DEM/Game/src/Scripting/Flow/LuaStringAction.h
	DEM/Game/src/Scripting/Flow/ScriptCondition.h
	DEM/Game/src/Scripting/Flow/SetVarAction.h
)

set(DEM_L2_GAME_SOURCES
	DEM/Game/src/AI/AILevel.cpp
	DEM/Game/src/AI/FormationManager.cpp
	DEM/Game/src/AI/MoveInteraction.cpp
	DEM/Game/src/AI/Behaviour/BehaviourTreeAsset.cpp
	DEM/Game/src/AI/Behaviour/BehaviourTreeAssetLoader.cpp
	DEM/Game/src/AI/Behaviour/BehaviourTreeCondition.cpp
	DEM/Game/src/AI/Behaviour/BehaviourTreeExecuteAbility.cpp
	DEM/Game/src/AI/Behaviour/BehaviourTreePlayer.cpp
	DEM/Game/src/AI/Behaviour/BehaviourTreeSelector.cpp
	DEM/Game/src/AI/Behaviour/BehaviourTreeSequence.cpp
	DEM/Game/src/AI/Movement/CharacterControlSystem.cpp
	DEM/Game/src/AI/Movement/SteerAction.cpp
	DEM/Game/src/AI/Navigation/NavAgentSettings.cpp
	DEM/Game/src/AI/Navigation/NavAgentSettingsLoaderHRD.cpp
	DEM/Game/src/AI/Navigation/NavigationSystem.cpp
	DEM/Game/src/AI/Navigation/NavMap.cpp
	DEM/Game/src/AI/Navigation/NavMesh.cpp
	DEM/Game/src/AI/Navigation/NavMeshDebugDraw.cpp
	DEM/Game/src/AI/Navigation/NavMeshLoaderNM.cpp
	DEM/Game/src/AI/Navigation/PathRequestQueue.cpp
	DEM/Game/src/AI/Perception/PerceptionSystems.cpp
	DEM/Game/src/Animation/TimelineTask.cpp
	DEM/Game/src/App/AppFSM.cpp
	DEM/Game/src/App/AppStateVideo.cpp
	DEM/Game/src/Game/ActionQueueSystem.cpp
	DEM/Game/src/Game/EntityOld.cpp
	DEM/Game/src/Game/GameLevel.cpp
	DEM/Game/src/Game/GameSession.cpp
	DEM/Game/src/Game/GameStateManager.cpp
	DEM/Game/src/Game/Property.cpp
	DEM/Game/src/Game/ECS/EntityTemplateLoader.cpp
	DEM/Game/src/Game/ECS/GameWorld.cpp
	DEM/Game/src/Game/Interaction/Ability.cpp
	DEM/Game/src/Game/Interaction/AbilityExecutionSystem.cpp
	DEM/Game/src/Game/Interaction/Interaction.cpp
	DEM/Game/src/Game/Interaction/InteractionManager.cpp
	DEM/Game/src/Game/Interaction/ScriptedAbility.cpp
	DEM/Game/src/Game/Interaction/ScriptedInteraction.cpp
	DEM/Game/src/Game/Interaction/SelectInteraction.cpp
	DEM/Game/src/Game/Interaction/Zone.cpp
	DEM/Game/src/Game/Objects/SmartObject.cpp
	DEM/Game/src/Game/Objects/SmartObjectLoader.cpp
	DEM/Game/src/Game/Objects/SmartObjectSystem.cpp
	DEM/Game/src/Physics/PhysicsSystems.cpp
	DEM/Game/src/Physics/PropTrigger.cpp
	DEM/Game/src/Physics/PropTriggerSI.cpp
	DEM/Game/src/Scene/SceneSystems.cpp
	DEM/Game/src/Scripting/EntityScriptObject.cpp
	DEM/Game/src/Scripting/PropScriptable.cpp
	DEM/Game/src/Scripting/ScriptObjectSIEx.cpp
	DEM/Game/src/Scripting/SolGame.cpp
	DEM/Game/src/Scripting/Flow/Condition.cpp
	DEM/Game/src/Scripting/Flow/ConditionRegistry.cpp
	DEM/Game/src/Scripting/Flow/FlowAssetLoader.cpp
	DEM/Game/src/Scripting/Flow/FlowPlayer.cpp
	DEM/Game/src/Scripting/Flow/HubAction.cpp
	DEM/Game/src/Scripting/Flow/LuaStringAction.cpp
	DEM/Game/src/Scripting/Flow/ScriptCondition.cpp
	DEM/Game/src/Scripting/Flow/SetVarAction.cpp
)

