set(DEM_L2_GAME_HEADERS
	DEM/Game/src/AI/ActorFwd.h
	DEM/Game/src/AI/AILevel.h
	DEM/Game/src/AI/AIServer.h
	DEM/Game/src/AI/AIStateComponent.h
	DEM/Game/src/AI/FormationManager.h
	DEM/Game/src/AI/MoveInteraction.h
	DEM/Game/src/AI/PassableTargetFilter.h
	DEM/Game/src/AI/PropActorBrain.h
	DEM/Game/src/AI/PropAIHints.h
	DEM/Game/src/AI/PropSmartObject.h
	DEM/Game/src/AI/Behaviour/Action.h
	DEM/Game/src/AI/Behaviour/ActionIdle.h
	DEM/Game/src/AI/Behaviour/ActionSequence.h
	DEM/Game/src/AI/Memory/MemFact.h
	DEM/Game/src/AI/Memory/MemSystem.h
	DEM/Game/src/AI/Movement/SteerAction.h
	DEM/Game/src/AI/Movement/Memory/MemFactObstacle.h
	DEM/Game/src/AI/Navigation/NavAgentComponent.h
	DEM/Game/src/AI/Navigation/NavAgentSettings.h
	DEM/Game/src/AI/Navigation/NavAgentSettingsLoaderHRD.h
	DEM/Game/src/AI/Navigation/NavControllerComponent.h
	DEM/Game/src/AI/Navigation/NavFwd.h
	DEM/Game/src/AI/Navigation/NavMap.h
	DEM/Game/src/AI/Navigation/NavMesh.h
	DEM/Game/src/AI/Navigation/NavMeshDebugDraw.h
	DEM/Game/src/AI/Navigation/NavMeshLoaderNM.h
	DEM/Game/src/AI/Navigation/PathRequestQueue.h
	DEM/Game/src/AI/Navigation/TraversalAction.h
	DEM/Game/src/AI/Perception/Perceptor.h
	DEM/Game/src/AI/Perception/Sensor.h
	DEM/Game/src/AI/Perception/Stimulus.h
	DEM/Game/src/AI/Planning/ActionTpl.h
	DEM/Game/src/AI/Planning/ActionTplIdle.h
	DEM/Game/src/AI/Planning/Goal.h
	DEM/Game/src/AI/Planning/GoalIdle.h
	DEM/Game/src/AI/Planning/Planner.h
	DEM/Game/src/AI/Planning/WorldState.h
	DEM/Game/src/AI/Planning/WorldStateSource.h
	DEM/Game/src/AI/Planning/WorldStateSourceScript.h
	DEM/Game/src/AI/SmartObj/SmartAction.h
	DEM/Game/src/AI/SmartObj/Actions/ActionGotoSmartObj.h
	DEM/Game/src/AI/SmartObj/Actions/ActionUseSmartObj.h
	DEM/Game/src/AI/SmartObj/ActionTpls/ActionTplGotoSmartObj.h
	DEM/Game/src/AI/SmartObj/ActionTpls/ActionTplUseSmartObj.h
	DEM/Game/src/Animation/AnimationComponent.h
	DEM/Game/src/Animation/TimelineTask.h
	DEM/Game/src/App/AppFSM.h
	DEM/Game/src/App/AppStateVideo.h
	DEM/Game/src/App/StateHandler.h
	DEM/Game/src/Game/Entity.h
	DEM/Game/src/Game/GameLevel.h
	DEM/Game/src/Game/GameSession.h
	DEM/Game/src/Game/GameState.h
	DEM/Game/src/Game/GameStateManager.h
	DEM/Game/src/Game/Property.h
	DEM/Game/src/Game/ECS/ComponentStorage.h
	DEM/Game/src/Game/ECS/Entity.h
	DEM/Game/src/Game/ECS/EntityMap.h
	DEM/Game/src/Game/ECS/EntityTemplate.h
	DEM/Game/src/Game/ECS/EntityTemplateLoader.h
	DEM/Game/src/Game/ECS/GameWorld.h
	DEM/Game/src/Game/ECS/Components/ActionQueueComponent.h
	DEM/Game/src/Game/ECS/Components/CharacterControllerComponent.h
	DEM/Game/src/Game/ECS/Components/RigidBodyComponent.h
	DEM/Game/src/Game/ECS/Components/SceneComponent.h
	DEM/Game/src/Game/Interaction/Interaction.h
	DEM/Game/src/Game/Interaction/InteractionContext.h
	DEM/Game/src/Game/Interaction/InteractionManager.h
	DEM/Game/src/Game/Interaction/InteractionTool.h
	DEM/Game/src/Game/Interaction/SelectableComponent.h
	DEM/Game/src/Game/Interaction/SelectableTargetFilter.h
	DEM/Game/src/Game/Interaction/SelectInteraction.h
	DEM/Game/src/Game/Interaction/TargetFilter.h
	DEM/Game/src/Game/Objects/SmartObject.h
	DEM/Game/src/Game/Objects/SmartObjectComponent.h
	DEM/Game/src/Game/Objects/SmartObjectInteraction.h
	DEM/Game/src/Game/Objects/SmartObjectLoader.h
	DEM/Game/src/Game/Objects/SmartObjectTargetFilter.h
	DEM/Game/src/Physics/PropPhysics.h
	DEM/Game/src/Physics/PropTrigger.h
	DEM/Game/src/Physics/TriggerContactCallback.h
	DEM/Game/src/Scene/PropSceneNode.h
	DEM/Game/src/Scene/Events/SetTransform.h
	DEM/Game/src/Scripting/EntityScriptObject.h
	DEM/Game/src/Scripting/PropScriptable.h
	DEM/Game/src/SI/SI_L2.h
	DEM/Game/src/UI/PropUIControl.h
)

set(DEM_L2_GAME_SOURCES
	DEM/Game/src/AI/AILevel.cpp
	DEM/Game/src/AI/AIServer.cpp
	DEM/Game/src/AI/FormationManager.cpp
	DEM/Game/src/AI/MoveInteraction.cpp
	DEM/Game/src/AI/PropActorBrain.cpp
	DEM/Game/src/AI/PropActorBrainSI.cpp
	DEM/Game/src/AI/PropAIHints.cpp
	DEM/Game/src/AI/PropAIHintsSI.cpp
	DEM/Game/src/AI/PropSmartObject.cpp
	DEM/Game/src/AI/PropSmartObjectSI.cpp
	DEM/Game/src/AI/Behaviour/ActionIdle.cpp
	DEM/Game/src/AI/Behaviour/ActionSequence.cpp
	DEM/Game/src/AI/Memory/MemFact.cpp
	DEM/Game/src/AI/Memory/MemSystem.cpp
	DEM/Game/src/AI/Movement/CharacterControlSystem.cpp
	DEM/Game/src/AI/Movement/SteerAction.cpp
	DEM/Game/src/AI/Movement/Memory/MemFactObstacle.cpp
	DEM/Game/src/AI/Navigation/NavAgentSettings.cpp
	DEM/Game/src/AI/Navigation/NavAgentSettingsLoaderHRD.cpp
	DEM/Game/src/AI/Navigation/NavigationSystem.cpp
	DEM/Game/src/AI/Navigation/NavMap.cpp
	DEM/Game/src/AI/Navigation/NavMesh.cpp
	DEM/Game/src/AI/Navigation/NavMeshDebugDraw.cpp
	DEM/Game/src/AI/Navigation/NavMeshLoaderNM.cpp
	DEM/Game/src/AI/Navigation/PathRequestQueue.cpp
	DEM/Game/src/AI/Planning/ActionTpl.cpp
	DEM/Game/src/AI/Planning/ActionTplIdle.cpp
	DEM/Game/src/AI/Planning/Goal.cpp
	DEM/Game/src/AI/Planning/GoalIdle.cpp
	DEM/Game/src/AI/Planning/Planner.cpp
	DEM/Game/src/AI/Planning/WorldState.cpp
	DEM/Game/src/AI/Planning/WorldStateSourceScript.cpp
	DEM/Game/src/AI/SmartObj/SmartAction.cpp
	DEM/Game/src/AI/SmartObj/Actions/ActionGotoSmartObj.cpp
	DEM/Game/src/AI/SmartObj/Actions/ActionUseSmartObj.cpp
	DEM/Game/src/AI/SmartObj/ActionTpls/ActionTplGotoSmartObj.cpp
	DEM/Game/src/AI/SmartObj/ActionTpls/ActionTplUseSmartObj.cpp
	DEM/Game/src/Animation/TimelineTask.cpp
	DEM/Game/src/App/AppFSM.cpp
	DEM/Game/src/App/AppStateVideo.cpp
	DEM/Game/src/Game/ActionQueueSystem.cpp
	DEM/Game/src/Game/EntityOld.cpp
	DEM/Game/src/Game/GameLevel.cpp
	DEM/Game/src/Game/GameSession.cpp
	DEM/Game/src/Game/GameStateManager.cpp
	DEM/Game/src/Game/Property.cpp
	DEM/Game/src/Game/ECS/EntityTemplateLoader.cpp
	DEM/Game/src/Game/ECS/GameWorld.cpp
	DEM/Game/src/Game/Interaction/Interaction.cpp
	DEM/Game/src/Game/Interaction/InteractionManager.cpp
	DEM/Game/src/Game/Interaction/SelectInteraction.cpp
	DEM/Game/src/Game/Objects/SmartObject.cpp
	DEM/Game/src/Game/Objects/SmartObjectInteraction.cpp
	DEM/Game/src/Game/Objects/SmartObjectInteractionSystem.cpp
	DEM/Game/src/Game/Objects/SmartObjectLoader.cpp
	DEM/Game/src/Game/Objects/SmartObjectSystem.cpp
	DEM/Game/src/Physics/PropPhysics.cpp
	DEM/Game/src/Physics/PropTrigger.cpp
	DEM/Game/src/Physics/PropTriggerSI.cpp
	DEM/Game/src/Scene/PropSceneNode.cpp
	DEM/Game/src/Scene/PropSceneNodeSI.cpp
	DEM/Game/src/Scripting/EntityScriptObject.cpp
	DEM/Game/src/Scripting/PropScriptable.cpp
	DEM/Game/src/Scripting/ScriptObjectSIEx.cpp
	DEM/Game/src/SI/SIEntityManager.cpp
	DEM/Game/src/SI/SINavMesh.cpp
	DEM/Game/src/UI/PropUIControl.cpp
	DEM/Game/src/UI/PropUIControlSI.cpp
)

