set(DEM_L3_RPG_HEADERS
	DEM/RPG/src/AI/Actions/ActionWander.h
	DEM/RPG/src/AI/ActionTpls/ActionTplWander.h
	DEM/RPG/src/AI/Goals/GoalWander.h
	DEM/RPG/src/AI/Goals/GoalWork.h
	DEM/RPG/src/AI/Memory/MemFactOverseer.h
	DEM/RPG/src/AI/Memory/MemFactSmartObj.h
	DEM/RPG/src/AI/Perceptors/PerceptorObstacle.h
	DEM/RPG/src/AI/Perceptors/PerceptorOverseer.h
	DEM/RPG/src/AI/Perceptors/PerceptorSmartObj.h
	DEM/RPG/src/AI/Sensors/SensorDamage.h
	DEM/RPG/src/AI/Sensors/SensorVision.h
	DEM/RPG/src/AI/Stimuli/StimulusSound.h
	DEM/RPG/src/AI/Stimuli/StimulusVisible.h
	DEM/RPG/src/Character/AppearanceAsset.h
	DEM/RPG/src/Character/AppearanceComponent.h
	DEM/RPG/src/Character/CharacterSheet.h
	DEM/RPG/src/Character/ModifiableParameter.h
	DEM/RPG/src/Character/ParameterModifier.h
	DEM/RPG/src/Character/SkillsComponent.h
	DEM/RPG/src/Character/SocialComponent.h
	DEM/RPG/src/Character/StatsComponent.h
	DEM/RPG/src/Combat/AttackAbility.h
	DEM/RPG/src/Combat/CombatUtils.h
	DEM/RPG/src/Combat/Damage.h
	DEM/RPG/src/Combat/DestructibleComponent.h
	DEM/RPG/src/Combat/WeaponComponent.h
	DEM/RPG/src/Conversation/ChoiceAction.h
	DEM/RPG/src/Conversation/ConversationManager.h
	DEM/RPG/src/Conversation/DisengageFromConversationAction.h
	DEM/RPG/src/Conversation/EngageInConversationAction.h
	DEM/RPG/src/Conversation/PhraseAction.h
	DEM/RPG/src/Conversation/TalkAbility.h
	DEM/RPG/src/Conversation/TalkingComponent.h
	DEM/RPG/src/Items/ArmorComponent.h
	DEM/RPG/src/Items/EquipmentChangesComponent.h
	DEM/RPG/src/Items/EquipmentComponent.h
	DEM/RPG/src/Items/EquipmentScheme.h
	DEM/RPG/src/Items/EquippableComponent.h
	DEM/RPG/src/Items/EquippedComponent.h
	DEM/RPG/src/Items/ItemComponent.h
	DEM/RPG/src/Items/ItemContainerComponent.h
	DEM/RPG/src/Items/ItemCountMonitorComponent.h
	DEM/RPG/src/Items/ItemManager.h
	DEM/RPG/src/Items/ItemStackComponent.h
	DEM/RPG/src/Items/ItemUtils.h
	DEM/RPG/src/Items/LockpickComponent.h
	DEM/RPG/src/Items/PickItemAbility.h
	DEM/RPG/src/Objects/LockComponent.h
	DEM/RPG/src/Objects/LockpickAbility.h
	DEM/RPG/src/Objects/OwnedComponent.h
	DEM/RPG/src/Quests/QuestData.h
	DEM/RPG/src/Quests/QuestManager.h
	DEM/RPG/src/Social/SocialManager.h
	DEM/RPG/src/World/WorldManager.h
)

set(DEM_L3_RPG_SOURCES
	DEM/RPG/src/AI/Actions/ActionWander.cpp
	DEM/RPG/src/AI/ActionTpls/ActionTplWander.cpp
	DEM/RPG/src/AI/Goals/GoalWander.cpp
	DEM/RPG/src/AI/Goals/GoalWork.cpp
	DEM/RPG/src/AI/Memory/MemFactOverseer.cpp
	DEM/RPG/src/AI/Memory/MemFactSmartObj.cpp
	DEM/RPG/src/AI/Perceptors/PerceptorObstacle.cpp
	DEM/RPG/src/AI/Perceptors/PerceptorOverseer.cpp
	DEM/RPG/src/AI/Perceptors/PerceptorSmartObj.cpp
	DEM/RPG/src/AI/Sensors/SensorVision.cpp
	DEM/RPG/src/AI/Stimuli/StimulusSound.cpp
	DEM/RPG/src/AI/Stimuli/StimulusVisible.cpp
	DEM/RPG/src/Combat/AttackAbility.cpp
	DEM/RPG/src/Combat/CombatUtils.cpp
	DEM/RPG/src/Conversation/ChoiceAction.cpp
	DEM/RPG/src/Conversation/ConversationManager.cpp
	DEM/RPG/src/Conversation/ConversationSystem.cpp
	DEM/RPG/src/Conversation/DisengageFromConversationAction.cpp
	DEM/RPG/src/Conversation/EngageInConversationAction.cpp
	DEM/RPG/src/Conversation/PhraseAction.cpp
	DEM/RPG/src/Conversation/TalkAbility.cpp
	DEM/RPG/src/Items/EquipmentSystem.cpp
	DEM/RPG/src/Items/ItemManager.cpp
	DEM/RPG/src/Items/ItemUtils.cpp
	DEM/RPG/src/Items/PickItemAbility.cpp
	DEM/RPG/src/Objects/LockpickAbility.cpp
	DEM/RPG/src/Quests/QuestManager.cpp
	DEM/RPG/src/Social/SocialManager.cpp
	DEM/RPG/src/World/WorldManager.cpp
)

