set(DEM_L3_RPG_HEADERS
	DEM/RPG/src/Character/AppearanceAsset.h
	DEM/RPG/src/Character/AppearanceComponent.h
	DEM/RPG/src/Character/Archetype.h
	DEM/RPG/src/Character/BoolStat.h
	DEM/RPG/src/Character/CharacterSheet.h
	DEM/RPG/src/Character/ModifiableParameter.h
	DEM/RPG/src/Character/NumericStat.h
	DEM/RPG/src/Character/ParameterModifier.h
	DEM/RPG/src/Character/SkillsComponent.h
	DEM/RPG/src/Character/SocialComponent.h
	DEM/RPG/src/Character/StatsComponent.h
	DEM/RPG/src/Character/StatusEffect.h
	DEM/RPG/src/Character/StatusEffectLogic.h
	DEM/RPG/src/Combat/AttackAbility.h
	DEM/RPG/src/Combat/CombatUtils.h
	DEM/RPG/src/Combat/Damage.h
	DEM/RPG/src/Combat/DestructibleComponent.h
	DEM/RPG/src/Combat/WeaponComponent.h
	DEM/RPG/src/Conversation/BarterAction.h
	DEM/RPG/src/Conversation/ChoiceAction.h
	DEM/RPG/src/Conversation/ConversationManager.h
	DEM/RPG/src/Conversation/DisengageFromConversationAction.h
	DEM/RPG/src/Conversation/EngageInConversationAction.h
	DEM/RPG/src/Conversation/PhraseAction.h
	DEM/RPG/src/Conversation/TalkAbility.h
	DEM/RPG/src/Conversation/TalkingComponent.h
	DEM/RPG/src/Items/ArmorComponent.h
	DEM/RPG/src/Items/EquipmentChangesComponent.h
	DEM/RPG/src/Items/EquipmentComponent.h
	DEM/RPG/src/Items/EquipmentScheme.h
	DEM/RPG/src/Items/EquippableComponent.h
	DEM/RPG/src/Items/EquippedComponent.h
	DEM/RPG/src/Items/ItemComponent.h
	DEM/RPG/src/Items/ItemContainerComponent.h
	DEM/RPG/src/Items/ItemCountMonitorComponent.h
	DEM/RPG/src/Items/ItemList.h
	DEM/RPG/src/Items/ItemManager.h
	DEM/RPG/src/Items/ItemStackComponent.h
	DEM/RPG/src/Items/ItemUtils.h
	DEM/RPG/src/Items/LockpickComponent.h
	DEM/RPG/src/Items/PickItemAbility.h
	DEM/RPG/src/Items/VendorComponent.h
	DEM/RPG/src/Items/VendorLogic.h
	DEM/RPG/src/Objects/LockComponent.h
	DEM/RPG/src/Objects/LockpickAbility.h
	DEM/RPG/src/Objects/OwnedComponent.h
	DEM/RPG/src/Quests/QuestData.h
	DEM/RPG/src/Quests/QuestManager.h
	DEM/RPG/src/Social/SocialManager.h
	DEM/RPG/src/Social/SocialUtils.h
	DEM/RPG/src/World/WorldManager.h
)

set(DEM_L3_RPG_SOURCES
	DEM/RPG/src/AI/PerceptionSystems.cpp
	DEM/RPG/src/Character/Archetype.cpp
	DEM/RPG/src/Character/BoolStat.cpp
	DEM/RPG/src/Character/CharacterSheet.cpp
	DEM/RPG/src/Character/CharacterSystems.cpp
	DEM/RPG/src/Character/NumericStat.cpp
	DEM/RPG/src/Character/StatusEffectLogic.cpp
	DEM/RPG/src/Combat/AttackAbility.cpp
	DEM/RPG/src/Combat/CombatUtils.cpp
	DEM/RPG/src/Conversation/BarterAction.cpp
	DEM/RPG/src/Conversation/ChoiceAction.cpp
	DEM/RPG/src/Conversation/ConversationManager.cpp
	DEM/RPG/src/Conversation/ConversationSystem.cpp
	DEM/RPG/src/Conversation/DisengageFromConversationAction.cpp
	DEM/RPG/src/Conversation/EngageInConversationAction.cpp
	DEM/RPG/src/Conversation/PhraseAction.cpp
	DEM/RPG/src/Conversation/TalkAbility.cpp
	DEM/RPG/src/Items/EquipmentSystem.cpp
	DEM/RPG/src/Items/ItemList.cpp
	DEM/RPG/src/Items/ItemManager.cpp
	DEM/RPG/src/Items/ItemUtils.cpp
	DEM/RPG/src/Items/PickItemAbility.cpp
	DEM/RPG/src/Items/VendorLogic.cpp
	DEM/RPG/src/Objects/LockpickAbility.cpp
	DEM/RPG/src/Quests/QuestManager.cpp
	DEM/RPG/src/Social/SocialManager.cpp
	DEM/RPG/src/Social/SocialUtils.cpp
	DEM/RPG/src/World/WorldManager.cpp
)

